import {
  BriefcaseBusiness,
  Bus,
  Car,
  Circle,
  CircleDollarSign,
  Coffee,
  CreditCard,
  Dumbbell,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HeartPulse,
  Home,
  House,
  Landmark,
  Laptop,
  List,
  Plane,
  PiggyBank,
  Plus,
  ReceiptText,
  Salad,
  Settings,
  Shirt,
  ShoppingBag,
  Sparkles,
  Smartphone,
  Soup,
  TrainFront,
  Utensils,
  WalletCards,
  Wifi,
  Wrench
} from 'lucide-react';

export const iconMap = {
  BriefcaseBusiness,
  Bus,
  Car,
  Circle,
  CircleDollarSign,
  Coffee,
  CreditCard,
  Dumbbell,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HeartPulse,
  Home,
  House,
  Landmark,
  Laptop,
  List,
  Plane,
  PiggyBank,
  Plus,
  ReceiptText,
  Salad,
  Settings,
  Shirt,
  ShoppingBag,
  Sparkles,
  Smartphone,
  Soup,
  TrainFront,
  Utensils,
  WalletCards,
  Wifi,
  Wrench
};

export function Icon({ name = 'Circle', className = 'h-5 w-5' }) {
  const Component = iconMap[name] || Circle;
  return <Component className={className} strokeWidth={2.3} />;
}

export const colorClasses = {
  amber: 'bg-amberSoft text-[#8A5A00]',
  sky: 'bg-skySoft text-[#25638F]',
  pink: 'bg-pinkSoft text-[#9D3F62]',
  mint: 'bg-mintSoft text-[#247047]',
  coral: 'bg-[#F8D6C8] text-coral',
  peach: 'bg-[#FFE0CC] text-[#9B4A25]',
  lavender: 'bg-[#EDE3FF] text-[#6D4AA0]',
  butter: 'bg-[#FFF2BF] text-[#8A6A00]',
  teal: 'bg-[#DDF6F3] text-[#26736B]',
  leaf: 'bg-[#E6F4D7] text-[#4F7D2C]'
};
